config/routes.rb
MangaSong::Application.routes.draw do
  resources :categories

  devise_for :users
  
  resources :musiques
  resources :comments, :only => [:create]

  root :to => 'musiques#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible  :music_id, :content
  validates :content, :presence => true
  belongs_to :musique, :foreign_key => 'music_id'
end

app/models/musique.rb
class Musique < ActiveRecord::Base
  attr_accessible :title, :name, :category_id 
  validates :name, :presence => true
  validates :title, :presence => true
  
  has_many :comments, :foreign_key => 'music_id'
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :pseudo
  # attr_accessible :title, :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  def display_music

  end
  
  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # POST /comments

  def create
    @comment = Comment.new(params[:comment])


      if @comment.save
         redirect_to @comment.musique, notice: 'Comment was successfully created.'
      else
         redirect_to @comment.musique, error: 'Comment was not successfully created.'
      end
    end
  end

  

app/controllers/musiques_controller.rb
class MusiquesController < ApplicationController
  # GET /musiques
  # GET /musiques.json
  def index
   
    @q = Musique.search(params[:q])
    @musiques = @q.result
    @musiques = @musiques.paginate(:page => params[:page], :per_page=>2)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musiques }
    end
  end
 
  # GET /musiques/1
  # GET /musiques/1.json
  def show
    @musique = Musique.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @musique }
    end
  end

  # GET /musiques/new
  # GET /musiques/new.json
  def new
    @musique = Musique.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @musique }
    end
  end

  # GET /musiques/1/edit
  def edit
    @musique = Musique.find(params[:id])
  end

  # POST /musiques
  # POST /musiques.json
  def create
    @musique = Musique.new
    @musique.title = params[:musique][:title]
    uploaded_io = params[:musique][:name]
    @musique.name = uploaded_io.original_filename

    File.open(Rails.root.join('public/music/', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    @musique.category_id = params[:musique][:category_id]
    respond_to do |format|

      if @musique.save
        format.html { redirect_to @musique, notice: 'Musique was successfully created.' }
        format.json { render json: @musique, status: :created, location: @musique }
      else
        format.html { render action: "new" }
        format.json { render json: @musique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musiques/1
  # PUT /musiques/1.json
  def update
    @musique = Musique.find(params[:id])

    respond_to do |format|
      if @musique.update_attributes(params[:musique])
        format.html { redirect_to @musique, notice: 'Musique was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @musique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musiques/1
  # DELETE /musiques/1.json
  def destroy
    @musique = Musique.find(params[:id])
    @musique.destroy

    respond_to do |format|
      format.html { redirect_to musiques_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/musiques_helper.rb
module MusiquesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<% @category.musiques.each do |musique| %>
    <br>
    	<%= musique.title %>
    	<%= musique.comments.count %>
    </br>
 <% end %>
</p>
<p>
  <b>Name:</b>
  <br><br>
  <%= @category.name %>
  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MangaSong" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/musiques#index">Manga Song</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, category  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Administration</h3>
              <ul class="nav nav-list">

                <% if user_signed_in? %>
                  <li class="nav-header"><%= current_user.email %></li>
                  <li><%= link_to "Modifer un compte", "/users/edit"  %></li>
                  <li><%= link_to "Se deconnecter", destroy_user_session_path, :method => :delete  %></li>
                <% else %>
                  <li><%= link_to "Creer un compte", new_user_registration_path  %></li>
                  <li><%= link_to "Se connecter", new_user_session_path  %></li>
                <% end %>

              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/musiques/_form.html.erb
<%= simple_form_for @musique do |f| %>
  
    <%= f.input :title %>
 
    <%= f.input :name, as: :file %>
   
    <%= f.association :category%>
  
    <%= f.submit %>

<% end %>

app/views/musiques/edit.html.erb
<h1>Editing musique</h1>

<%= render 'form' %>

<%= link_to 'Show', @musique %> |
<%= link_to 'Back', musiques_path %>

app/views/musiques/index.html.erb
<h1>Manga Songs</h1>

<div>
 <%= search_form_for @q do |f| %>

  <%= f.label 'Rechercher une musique :' %>

  <%= f.text_field :title_cont %>

  <%= f.submit %>

<% end %>
 </div>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musiques.each do |musique| %>
  <tr>
    <td><%= musique.title %></td>
    <td><%= musique.comments.count %></td>
    <td><audio controls id="video1"
  src="\music\<%= musique.name%>">
Your user agent does not support the HTML5 Audio element.
</audio> </td>
    <% if user_signed_in? %>
    <td><%= link_to 'Show', musique %></td>
    <td><%= link_to 'Edit', edit_musique_path(musique) %></td>
    <td><%= link_to 'Destroy', musique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <% end %>
  </tr>
<% end %>
</table>

<p>musique en cours :</p>

<%= will_paginate @musiques %>

<br />
<% if user_signed_in? %>
  <%= link_to 'New Musique', new_musique_path %>
<% else %>
<% end %>

app/views/musiques/new.html.erb
<h1>New musique</h1>

<%= render 'form' %>

<%= link_to 'Back', musiques_path %>

app/views/musiques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @musique.title %>
</p>

<p>
  <b>chemin:</b>
  <%= @musique.name %>
</p>

<ul>
	<% @musique.comments.each do |musique| %>
		<li> <%= musique.content %> </li>
	<%end%>
</ul>

<%= simple_form_for @musique.comments.new do |f| %>
	<%= f.hidden_field :music_id, :value => @musique.id %>
	<%= f.input :content %>
  <%= f.submit %>
<%end%>


<%= link_to 'Edit', edit_musique_path(@musique) %> |
<%= link_to 'Back', musiques_path %>